import "./globals.css";
import Sidebar from "./components/Sidebar";
import { slabo } from "./ui/fonts";
import { Providers } from "./ui/providers";

export const metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex min-h-screen max-w-screen ${slabo.className} dark:bg-white`}>
        <Providers>
          <Sidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
