import "./globals.css";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen max-w-screen">
          <Sidebar />
          {children}
      </body>
    </html>
  );
}
