import "./globals.css";
import Sidebar from "./components/Sidebar";
import { slabo } from "./ui/fonts";
import { Providers } from "./ui/providers";

export const metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex min-h-screen max-w-screen ${slabo.className} dark:bg-gray-900 text-gray-900 dark:text-gray-200 transition-all duration-300`}>
        <Providers>
          <div className="flex flex-wrap">
            <Sidebar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
